---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: nmstate-operator-sub
  namespace: openshift-nmstate
  labels:
    operators.coreos.com/kubernetes-nmstate-operator.openshift-nmstate: ""
  annotations:
    ran.openshift.io/ztp-deploy-wave: "2"
spec:
  channel: stable
  name: kubernetes-nmstate-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Manual
status:
  state: AtLatestKnown
