---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: standard
  labels:
    machineconfiguration.openshift.io/role: standard
    pools.operator.machineconfiguration.openshift.io/standard: ""
spec:
  maxUnavailable: 90%
  machineConfigSelector:
    matchExpressions:
      - key: machineconfiguration.openshift.io/role
        operator: In
        values:
          - worker
          - standard
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/standard: ""
  paused: true
