---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: ht100gb
  name: vfio-virt-noiommu
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,b3B0aW9ucyB2ZmlvIGVuYWJsZV91bnNhZmVfbm9pb21tdV9tb2RlPTEKb3B0aW9ucyB2ZmlvX2lvbW11X3R5cGUxIGFsbG93X3Vuc2FmZV9pbnRlcnJ1cHRzPTEK
        mode: 420
        overwrite: true
        path: /etc/modprobe.d/vfio.conf
