---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: ht100gb
  labels:
    machineconfiguration.openshift.io/role: ht100gb
    pools.operator.machineconfiguration.openshift.io/ht100gb: ""
spec:
  maxUnavailable: 90%
  machineConfigSelector:
    matchExpressions:
      - key: machineconfiguration.openshift.io/role
        operator: In
        values:
          - worker
          - ht100gb
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/ht100gb: ""
  paused: false
