---
# apiVersion: config.openshift.io/v1
# kind: ImageDigestMirrorSet
# metadata:
#   name: replace-metallb-images
# spec:
#   imageDigestMirrors:
#   - mirrors:
#       - quay.io/karampok/controller
#     source: quay.io/metallb/controller
#     mirrorSourcePolicy: NeverContactSource
#     pullFromMirror: DigestOnly
---
apiVersion: config.openshift.io/v1
kind: ImageDigestMirrorSet
metadata:
  name: my-metallb-operator
spec:
  imageTagMirrors:
  - mirrors:
      - brew.redhat.io/openshift4/metallb-rhel9-operator
    source: quay.io/karampok/metallb-rhel9-operator
    mirrorSourcePolicy: NeverContactSource
    pullFromMirror: DigestOnly
