---
apiVersion: v1beta1
kind: ImageBasedInstallationConfig
metadata:
  name: image-based-installation-config
seedImage: quay.io/openshift-kni/image-based-seeds:4.18
seedVersion: 4.18.6
installationDisk: "/dev/vda"
extraPartitionLabel: var-lib-containers
pullSecret: "PULLSECRET"
sshKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICGjoGIRGSfiJ8Tv+Qd6S36xuGmeIuFL8w75shdhxy5l ci@only.com"
networkConfig:
  interfaces:
    - name: enp1s0
      type: ethernet
      state: up
      mac-address: AA:BB:CC:DD:EE:01
      ipv4:
        enabled: true
        # address:
        #   - ip: 10.10.10.225
        #     prefix-length: 24
        dhcp: true
      ipv6:
        enabled: false
