---
apiVersion: v1beta1
kind: ImageBasedConfig
metadata:
  name: sno-imagebased-config
  namespace: cluster0
hostname: sno
releaseRegistry: quay.io
networkConfig:
  interfaces:
    - name: enp1s0
      type: ethernet
      state: up
      mac-address: AA:BB:CC:DD:EE:01
      ipv4:
        enabled: true
        address:
          #   - ip: 10.10.10.225
          #   prefix-length: 24
        dhcp: true
      ipv6:
        enabled: false
