# ---
# apiVersion: metallb.io/v1beta1
# kind: BFDProfile
# metadata:
#   name: bfd-profile
#   namespace: metallb-system
# spec:
#   receiveInterval: 300
#   transmitInterval: 300
#   detectMultiplier: 3
#   echoInterval: 300
#   echoMode: false
#   passiveMode: false
#   minimumTtl: 254
---
apiVersion: metallb.io/v1beta1
kind: BGPPeer
metadata:
  name: green
  namespace: metallb-system
spec:
  peerAddress: 10.10.1.1
  peerASN: 65001
  myASN: 7003
  # holdTime: "180s"
  # bfdProfile: bfd-profile
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bgpextras
  namespace: metallb-system
data:
  extras: |
    route-map 10.10.1.1-in permit 2
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: green
  namespace: metallb-system
spec:
  ipAddressPools:
    - green
  peers:
    - green
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: green
  namespace: metallb-system
spec:
  autoAssign: false
  addresses:
    - 5.5.5.1/32
    - 5.5.5.2/32
