---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bigfiles
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bigfile
  template:
    metadata:
      labels:
        app: bigfile
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      volumes:
        - name: data
          emptyDir:
            sizeLimit: 500Mi
      initContainers:
        - name: create-big-file
          image: quay.io/karampok/snife:latest
          command: ['sh', '-c', "dd if=/dev/zero of=/data/big.iso  bs=1024 count=0 seek=102400"]
          volumeMounts:
            - name: data
              mountPath: "/data"
      containers:
        - name: server
          securityContext:
            privileged: true
          image: quay.io/karampok/snife:latest
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          command: ["/bin/bash"]
          args: ["-c", "cd /data && python3 -m http.server 9000"]
          volumeMounts:
            - name: data
              mountPath: "/data"
          ports:
            - name: http
              containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: green
  name: greensvc-icmp-mtu-local
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: bigfile
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: green
  name: greensvc-icmp-mtu-cluster
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: bigfile
