[allowlist]
  description = "Global Allowlist"

  # Ignore based on any subset of the file path
  paths = [
    # Ignore all example certs
    '''telco-ocp-lab''',
    '''\/opt/sushy/.*$''',
  ]
        
  # Ignore based on any subset of the line
  regexes = [ ]
