[allowlist]
  description = "Global Allowlist"

  # Ignore based on any subset of the file path
  paths = [
    # Ignore all example certs
    '''sinfra''',
  ]
        
  # Ignore based on any subset of the line
  regexes = [ ]
