apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 10-br-ex-sno
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
      - path: /etc/nmstate/openshift/cluster.yml
        mode: 0644
        overwrite: true
        contents:
          source: data:text/plain;charset=utf-8;base64,aW50ZXJmYWNlczoKLSBuYW1lOiBlbnAxczAKICB0eXBlOiBldGhlcm5ldAogIHN0YXRlOiB1cAogIGlwdjQ6CiAgICBlbmFibGVkOiBmYWxzZQogIGlwdjY6CiAgICBlbmFibGVkOiBmYWxzZQotIG5hbWU6IGJvbmQwCiAgdHlwZTogYm9uZAogIHN0YXRlOiB1cAogIGlwdjQ6CiAgICBlbmFibGVkOiBmYWxzZQogIGlwdjY6CiAgICBlbmFibGVkOiBmYWxzZQogIGxpbmstYWdncmVnYXRpb246CiAgICBtb2RlOiBhY3RpdmUtYmFja3VwCiAgICBwb3J0OgogICAgLSBlbnAxczAKLSBuYW1lOiBici1leAogIHR5cGU6IG92cy1icmlkZ2UKICBzdGF0ZTogdXAKICBjb3B5LW1hYy1mcm9tOiBib25kMAogIGlwdjQ6CiAgICBlbmFibGVkOiB0cnVlCiAgICBkaGNwOiBmYWxzZQogICAgYWRkcmVzczoKICAgIC0gaXA6IDEwLjEwLjEwLjIyNQogICAgICBwcmVmaXgtbGVuZ3RoOiAyNAogIGlwdjY6CiAgICBlbmFibGVkOiBmYWxzZQogIGJyaWRnZToKICAgIHBvcnQ6CiAgICAtIG5hbWU6IGJvbmQwCiAgICAtIG5hbWU6IGJyLWV4Ci0gbmFtZTogYnItZXgKICB0eXBlOiBvdnMtaW50ZXJmYWNlCiAgc3RhdGU6IHVwCiAgaXB2NDoKICAgIGVuYWJsZWQ6IHRydWUKICAgIGRoY3A6IGZhbHNlCiAgICBhZGRyZXNzOgogICAgLSBpcDogMTAuMTAuMTAuMjI1CiAgICAgIHByZWZpeC1sZW5ndGg6IDI0CiAgaXB2NjoKICAgIGVuYWJsZWQ6IGZhbHNlCmRucy1yZXNvbHZlcjoKICBjb25maWc6CiAgICBzZXJ2ZXI6CiAgICAtIDEwLjEwLjIwLjEwCnJvdXRlczoKICBjb25maWc6CiAgLSBkZXN0aW5hdGlvbjogMC4wLjAuMC8wCiAgICBuZXh0LWhvcC1hZGRyZXNzOiAxMC4xMC4xMC4xCiAgICBuZXh0LWhvcC1pbnRlcmZhY2U6IGJyLWV4Cg==
