---
apiVersion: operator.openshift.io/v1
kind: Network
metadata:
  name: cluster
  annotations:
    ran.openshift.io/ztp-deploy-wave: "1"
spec:
  defaultNetwork:
    ovnKubernetesConfig:
      gatewayConfig:
        ipForwarding: "Global"
        routingViaHost: true
    type: OVNKubernetes
