apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: vfio-virt-noiommu
spec:
  config:
    ignition:
      version: 3.2.0
    systemd:
      units:
      - enabled: true
        name: vfio-virt-noiommu
        contents: |
          [Unit]
          Description=vfio no-iommu
          Before=kubelet.service crio.service node-valid-hostname.service

          [Service]
          # Need oneshot to delay kubelet
          Type=oneshot
          ExecStart=/usr/bin/bash -c "modprobe vfio enable_unsafe_noiommu_mode=1"
          StandardOutput=journal+console
          StandardError=journal+console

          [Install]
          WantedBy=network-online.target
