---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generators:
  - common.yaml
  - config-st-nodes.yaml
  - config-ht-nodes.yaml
  - config-metallb.yaml
  - deploy-odf.yaml
  - post.yaml
  - upgrade-cluster.yaml
  - validate.yaml
resources:
  - resources/ns.yaml
