---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "cluster"
  namespace: "ztp-common"
spec:
  bindingRules:
    common: "true"
  remediationAction: inform
  sourceFiles:
    - fileName: ClusterVersion.yaml
      policyName: "ocp-version"
      metadata:
        name: version
      spec:
        channel: "stable-4.14"
        desiredUpdate:
          version: 4.14.6
      status:
        history:
          - version: 4.14.6
            state: "Completed"
