---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "htworker"
  namespace: "ztp-group"
spec:
  bindingRules:
    htworker: ""
  remediationAction: inform
  mcp: "ht100gb"
  sourceFiles:
    - fileName: MachineConfigGeneric.yaml
      policyName: config-virt-vfio-noiommu-w1
      metadata:
        annotations:
          ran.openshift.io/ztp-deploy-wave: "1"
        labels:
          machineconfiguration.openshift.io/role: ht100gb
        name: vfio-virt-noiommu
      spec:
        config:
          ignition:
            version: 3.2.0
          storage:
            files:
              - contents:
                  source: data:text/plain;charset=utf-8;base64,b3B0aW9ucyB2ZmlvIGVuYWJsZV91bnNhZmVfbm9pb21tdV9tb2RlPTEKb3B0aW9ucyB2ZmlvX2lvbW11X3R5cGUxIGFsbG93X3Vuc2FmZV9pbnRlcnJ1cHRzPTEK
                mode: 420
                overwrite: true
                path: /etc/modprobe.d/vfio.conf
    # configure SR-IOV
    - fileName: SriovSupportedNicCM.yaml
      policyName: "patch-sriov-cm-hack-w3"
    - fileName: SriovOperatorConfig.yaml
      policyName: "config-operator-sriov-w10"
      spec:
        enableOperatorWebhook: false
        logLevel: 0
    - fileName: SriovNetwork.yaml
      policyName: config-sriov-sn-w100
      metadata:
        name: "leftnet"
      spec:
        resourceName: sriovleftdpdk
    - fileName: SriovNetwork.yaml
      policyName: config-sriov-sn-w100
      metadata:
        name: "rightnet"
      spec:
        resourceName: sriovrightdpdk
    - fileName: SriovNetworkNodePolicy.yaml
      policyName: config-sriov-snnp-w100
      metadata:
        name: sriovleftdpdk
      spec:
        resourceName: sriovleftdpdk
        nodeSelector:
          node-role.kubernetes.io/ht100gb: ""
        numVfs: 4
        priority: 99
        nicSelector:
          pfNames: ['enp41s0']
        deviceType: vfio-pci
    - fileName: SriovNetworkNodePolicy.yaml
      policyName: config-sriov-snnp-w100
      metadata:
        name: sriovrightdpdk
      spec:
        resourceName: sriovrightdpdk
        nodeSelector:
          node-role.kubernetes.io/ht100gb: ""
        numVfs: 4
        priority: 99
        nicSelector:
          pfNames: ['enp42s0']
        deviceType: vfio-pci
    # configure MachineConfigPools
    - fileName: MachineConfigPool.yaml
      policyName: config-nodes-w1
      metadata:
        name: ht100gb
        annotations:
          ran.openshift.io/ztp-deploy-wave: "1"
        labels:
          machineconfiguration.openshift.io/role: ht100gb
          pools.operator.machineconfiguration.openshift.io/ht100gb: ""
      spec:
        machineConfigSelector:
          matchExpressions:
            - key: machineconfiguration.openshift.io/role
              operator: In
              values: [worker, ht100gb]
        nodeSelector:
          matchLabels:
            node-role.kubernetes.io/ht100gb: ""
    - fileName: PerformanceProfile.yaml
      policyName: config-performanceprofile-w10
      complianceType: mustonlyhave
      metadata:
        name: ht100gb
        annotations:
          kubeletconfig.experimental: |
            {"systemReserved": {"memory": "2Gi"}, "topologyManagerScope": "pod"}
      spec:
        additionalKernelArgs: []
        cpu:
          isolated: "4-23"
          reserved: "0-3"
        hugepages:
          defaultHugepagesSize: 1G
          pages:
            - size: 1G
              count: 3
        numa:
          topologyPolicy: single-numa-node
        workloadHints:
          realTime: false
          highPowerConsumption: false
          perPodPowerManagement: false
        realTimeKernel:
          enabled: false
