---
generators:
  - common.yaml
  - label-nodes.yaml
  - config-ht-nodes.yaml
  - config-metallb.yaml
  - deploy-odf.yaml
  - post.yaml
  - upgrade-cluster.yaml
resources:
  - resources/ns.yaml
patches:
  - target:
      kind: PlacementRule
    patch: |-
      - op: add
        path: /metadata/version
        value: version-1

