---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hub-provision
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: hub
    repoURL: 'https://github.com/karampok/telco-ocp-lab.git'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 1
        maxDuration: 3m0s
      limit: 1000
