frr defaults datacenter
hostname gw1
log file /tmp/frr.log debugging
log timestamp precision 3

debug zebra events
debug zebra kernel
debug zebra rib
debug zebra nht
debug zebra nexthop
debug bgp keepalives
debug bgp neighbor-events
debug bgp nht
debug bgp updates in
debug bgp updates out
debug bgp zebra
debug bfd peer
debug bfd zebra
debug bfd network
!
ipv6 forwarding
!
interface eth0
 ipv6 nd ra-interval 30
 ipv6 nd ra-lifetime 0
 no ipv6 nd suppress-ra
exit
!
ip router-id 10.10.30.1
!
!
router bgp 65001
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 no bgp network import-check

 neighbor METALLB peer-group
 neighbor METALLB passive
 neighbor METALLB remote-as external
 neighbor METALLB advertisement-interval 1
 neighbor METALLB timers 30 90
 neighbor METALLB bfd
 neighbor METALLB bfd profile default

 neighbor 10.10.30.100 peer-group METALLB
 !
 address-family ipv4 unicast
  network 10.10.20.0/24
  neighbor METALLB activate
 exit-address-family
 !
 address-family ipv6 unicast
  network 2600:10:10:20::/64
  neighbor METALLB activate
 exit-address-family
exit
!
bfd
 profile default
  passive-mode
  echo transmit-interval 300
  echo receive-interval 300
 exit
exit
