---
apiVersion: v1alpha1
metadata:
  name: mno
additionalNTPSources:
  - 10.11.160.238
  - 10.2.32.37
rendezvousIP: 10.10.30.230
hosts:
  - hostname: mno-master-0
    role: master
    rootDeviceHints:
      deviceName: "/dev/vda"
    interfaces:
      - name: random
        macAddress: 16:ef:73:7f:92:cb
    networkConfig:
      interfaces:
        - name: random
          type: ethernet
          state: up
          ipv4:
            enabled: false
          ipv6:
            enabled: false
        - name: vlan30
          type: vlan
          state: up
          vlan:
            base-iface: random
            id: 30
          ipv4:
            enabled: true
            address:
              - ip: 10.10.30.230
                prefix-length: 24
            dhcp: false
          ipv6:
            enabled: true
            address:
              - ip: 2600:10:10:30::230
                prefix-length: 64
            dhcp: false
            autoconf: false
      dns-resolver:
        config:
          server:
            - 10.10.20.10
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 10.10.30.1
            next-hop-interface: vlan30
            table-id: 254
          - destination: ::/0
            next-hop-address: 2600:10:10:30::1
            next-hop-interface: vlan30
            table-id: 254
  - hostname: mno-master-1
    role: master
    rootDeviceHints:
      deviceName: "/dev/vda"
    interfaces:
      - name: random
        macAddress: 8e:a3:23:43:eb:f5
    networkConfig:
      interfaces:
        - name: random
          type: ethernet
          state: up
          ipv4:
            enabled: false
          ipv6:
            enabled: false
        - name: vlan30
          type: vlan
          state: up
          vlan:
            base-iface: random
            id: 30
          ipv4:
            enabled: true
            address:
              - ip: 10.10.30.231
                prefix-length: 24
            dhcp: false
          ipv6:
            enabled: true
            address:
              - ip: 2600:10:10:30::231
                prefix-length: 64
            dhcp: false
            autoconf: false
      dns-resolver:
        config:
          server:
            - 10.10.20.10
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 10.10.30.1
            next-hop-interface: vlan30
            table-id: 254
          - destination: ::/0
            next-hop-address: 2600:10:10:30::1
            next-hop-interface: vlan30
            table-id: 254
  - hostname: mno-master-2
    role: master
    rootDeviceHints:
      deviceName: "/dev/vda"
    interfaces:
      - name: random
        macAddress: 0e:49:1e:d3:80:b5
    networkConfig:
      interfaces:
        - name: random
          type: ethernet
          state: up
          ipv4:
            enabled: false
          ipv6:
            enabled: false
        - name: vlan30
          type: vlan
          state: up
          vlan:
            base-iface: random
            id: 30
          ipv4:
            enabled: true
            address:
              - ip: 10.10.30.232
                prefix-length: 24
            dhcp: false
          ipv6:
            enabled: true
            address:
              - ip: 2600:10:10:30::232
                prefix-length: 64
            dhcp: false
            autoconf: false
      dns-resolver:
        config:
          server:
            - 10.10.20.10
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 10.10.30.1
            next-hop-interface: vlan30
            table-id: 254
          - destination: ::/0
            next-hop-address: 2600:10:10:30::1
            next-hop-interface: vlan30
            table-id: 254
  - hostname: mno-worker-0
    role: worker
    rootDeviceHints:
      deviceName: "/dev/vda"
    interfaces:
      - name: random
        macAddress: 76:de:12:94:0b:7c
    networkConfig:
      interfaces:
        - name: random
          type: ethernet
          state: up
          ipv4:
            enabled: false
          ipv6:
            enabled: false
        - name: vlan30
          type: vlan
          state: up
          vlan:
            base-iface: random
            id: 30
          ipv4:
            enabled: true
            address:
              - ip: 10.10.30.233
                prefix-length: 24
            dhcp: false
          ipv6:
            enabled: true
            address:
              - ip: 2600:10:10:30::233
                prefix-length: 64
            dhcp: false
            autoconf: false
      dns-resolver:
        config:
          server:
            - 10.10.20.10
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 10.10.30.1
            next-hop-interface: vlan30
            table-id: 254
          - destination: ::/0
            next-hop-address: 2600:10:10:30::1
            next-hop-interface: vlan30
            table-id: 254
