---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "common"
  namespace: "ztp-common"
spec:
  bindingRules:
    common: "true"
  remediationAction: inform
  sourceFiles:
    - fileName: "MastersSchedulable.yaml"
      policyName: "config-cluster"
    - fileName: metallb/ns.yaml
      policyName: "install-operators"
    - fileName: metallb/operatorGroup.yaml
      policyName: "install-operators"
    - fileName: metallb/subscription.yaml
      policyName: "install-operators"
    - fileName: metallb/instance.yaml
      policyName: "install-operators"
    - fileName: nmstate/subscription.yaml
      policyName: "install-operators"
    - fileName: nmstate/ns.yaml
      policyName: "install-operators"
    - fileName: nmstate/operatorGroup.yaml
      policyName: "install-operators"
    - fileName: nmstate/instance.yaml
      policyName: "install-operators"
    - fileName: RoutingViaHost.yaml
      policyName: "config-network"
    - fileName: AddAdditionalNetworks.yaml
      policyName: "config-network"
      spec:
        additionalNetworks:
          - name: mh-macvlan
            namespace: default
            rawCNIConfig: '{ "cniVersion": "0.3.1", "name": "macvlan", "plugins": [ {"type": "macvlan","master": "bond0.11", "mtu": 1500, "mode": "bridge", "ipam": { "type": "whereabouts", "range": "2520:41:0:2106::/64","gateway": "2520:41:0:2106::1" } }, {"type":"tuning","sysctl":{"net.ipv6.conf.IFNAME.accept_ra":"0"}} ]}'
            type: Raw
    - fileName: ReduceMonitoringFootprint.yaml
      policyName: "config-policy"
    - fileName: ClusterVersion.yaml
      policyName: "platform-upgrade"
      metadata:
        name: version
      spec:
        channel: "fast-4.13"
        upstream: https://api.openshift.com/api/upgrades_info/v1/graph # default upstream.
        desiredUpdate:
          version: 4.13.4
      status:
        history:
          - version: 4.13.4
            state: "Completed"
