---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "common"
  namespace: "ztp-common"
spec:
  bindingRules:
    common: "true"
  remediationAction: inform
  sourceFiles:
    - fileName: "MastersSchedulable.yaml"
      policyName: "config-cluster"
    - fileName: ReduceMonitoringFootprint.yaml
      policyName: "config-policy"
    # install and configure SR-IOV operator
    - fileName: SriovSubscriptionNS.yaml
      policyName: "install-operators"
    - fileName: SriovSupportedNicCM.yaml
      policyName: "install-operators"
    - fileName: SriovSubscriptionOperGroup.yaml
      policyName: "install-operators"
    - fileName: SriovSubscription.yaml
      policyName: "install-operators"
    - fileName: SriovOperatorConfig.yaml
      policyName: "config-operators"
      spec:
        configDaemonNodeSelector:
          node-role.kubernetes.io/ht100gb: ""
    - fileName: metallb/ns.yaml
      policyName: "install-operators"
    - fileName: metallb/operatorGroup.yaml
      policyName: "install-operators"
    - fileName: metallb/subscription.yaml
      policyName: "install-operators"
    - fileName: metallb/instance.yaml
      policyName: "config-operators"
      spec:
        logLevel: debug
        speakerTolerations:
          - effect: NoSchedule
            key: sriov
            value: "true"
    # install NMState operator
    - fileName: nmstate/subscription.yaml
      policyName: "install-operators"
    - fileName: nmstate/ns.yaml
      policyName: "install-operators"
    - fileName: nmstate/operatorGroup.yaml
      policyName: "install-operators"
    - fileName: nmstate/instance.yaml
      policyName: "config-operators"
    # other networking config
    - fileName: RoutingViaHost.yaml
      policyName: "config-network"
    - fileName: AddAdditionalNetworks.yaml
      policyName: "config-network"
      spec:
        additionalNetworks:
          - name: mh-macvlan
            namespace: default
            rawCNIConfig: '{ "cniVersion": "0.3.1", "name": "macvlan", "plugins": [ {"type": "macvlan","master": "bond0.11", "mtu": 1500, "mode": "bridge", "ipam": { "type": "whereabouts", "range": "2520:41:0:2106::/64","gateway": "2520:41:0:2106::1" } }, {"type":"tuning","sysctl":{"net.ipv6.conf.IFNAME.accept_ra":"0"}} ]}'
            type: Raw
