---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "htworker"
  namespace: "ztp-group"
spec:
  bindingRules:
    htworker: ""
  remediationAction: inform
  mcp: "ht100gb"
  sourceFiles:
    # configure SR-IOV
    - fileName: SriovNetwork.yaml
      policyName: config-sriov
      metadata:
        name: "leftnet"
      spec:
        resourceName: sriovleftdpdk
    - fileName: SriovNetworkNodePolicy.yaml
      policyName: config-sriov
      metadata:
        name: sriovleftdpdk
      spec:
        resourceName: sriovleftdpdk
        nodeSelector:
          node-role.kubernetes.io/ht100gb: ""
        # mtu: 1492  # maybe bug in ixgbe driver
        numVfs: 4
        nicSelector:
          pfNames: ['enp41s0']
        deviceType: netdevice
    # configure MachineConfigPools
    - fileName: MachineConfigPool.yaml
      policyName: config-nodes
      metadata:
        name: ht100gb
        labels:
          machineconfiguration.openshift.io/role: ht100gb
          pools.operator.machineconfiguration.openshift.io/ht100gb: ""
      spec:
        machineConfigSelector:
          matchExpressions:
            - key: machineconfiguration.openshift.io/role
              operator: In
              values: [worker, ht100gb]
        nodeSelector:
          matchLabels:
            node-role.kubernetes.io/ht100gb: ""
    - fileName: PerformanceProfile.yaml
      policyName: config-nodes
      metadata:
        name: ht100gb
        annotations:
          kubeletconfig.experimental: |
            {"systemReserved": {"memory": "6Gi"}, "topologyManagerScope": "pod"}
      spec:
        cpu:
          isolated: "4-23"
          reserved: "0-3"
        hugepages:
          defaultHugepagesSize: 1G
          pages:
            - size: 1G
              count: 3
        numa:
          topologyPolicy: single-numa-node
        workloadHints:
          realTime: false
          highPowerConsumption: false
          perPodPowerManagement: false
        realTimeKernel:
          enabled: false
