---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "htworker"
  namespace: "ztp-group"
spec:
  bindingRules:
    htworker: ""
  remediationAction: inform
  mcp: "ht100gb"
  sourceFiles:
    - fileName: MachineConfigPool.yaml
      policyName: "config-nodes"
      metadata:
        name: ht100gb
        labels:
          machineconfiguration.openshift.io/role: ht100gb
      spec:
        machineConfigSelector:
          matchExpressions:
            - key: machineconfiguration.openshift.io/role
              operator: In
              values: [worker, ht100gb]
        nodeSelector:
          matchLabels:
            node-role.kubernetes.io/ht100gb: ""
    - fileName: PerformanceProfile.yaml
      policyName: "config-nodes"
      metadata:
        name: performance-ht100gb
        annotations:
          kubeletconfig.experimental: |
            {"systemReserved": {"memory": "6Gi"}, "topologyManagerScope": "pod"}`
      spec:
        additionalKernelArgs:
          - "nohz_full=4-15"
        cpu:
          isolated: "4-23"
          reserved: "0-3"
        hugepages:
          defaultHugepagesSize: 1G
          pages:
            - size: 2G
              count: 4
        numa:
          topologyPolicy: single-numa-node
        workloadHints:
          realTime: false
          highPowerConsumption: false
          perPodPowerManagement: false
        realTimeKernel:
          enabled: false
    # https://github.com/openshift-kni/cnf-features-deploy/blob/efe8c5ddcad32b5d0b8c58f51d391aafc96fe77d/ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml#L124-L140
    # https://github.com/openshift-kni/cnf-features-deploy/blob/efe8c5ddcad32b5d0b8c58f51d391aafc96fe77d/ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml#L196-L221
