---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "label-ht-worker"
  namespace: "ztp-site"
spec:
  bindingRules:
    sites: "n95"
  remediationAction: inform
  sourceFiles:
    # - fileName: LabelNode.yaml
    #   policyName: "label-nodes"
    #   metadata:
    #     name: "w1.5gc.eric.vlab"
    #     labels:
    #       node-role.kubernetes.io/standard: ""
    #       acm-policy-labels-workaround: enabled
    - fileName: LabelNode.yaml
      policyName: "label-nodes"
      metadata:
        name: "w0.5gc.eric.vlab"
        labels:
          node-role.kubernetes.io/ht100gb: ""
          acm-policy-labels-workaround: enabled
      spec:
        taints:
          - effect: NoSchedule
            key: sriov
            value: "true"
