---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "label-ht-worker"
  namespace: "ztp-site"
spec:
  bindingRules:
    sites: "n95"
  remediationAction: inform
  sourceFiles:
    - fileName: LabelHTNode.yaml
      policyName: "label-nodes"
      metadata:
        name: "5gc-w0"
        labels:
          node-role.kubernetes.io/ht100gb: ""
          type: "prod"
      spec:
        taints:
          - effect: NoSchedule
            key: sriov
            value: "true"
