---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "post"
  namespace: "ztp-common"
spec:
  bindingRules:
    common: "true"
  remediationAction: inform
  sourceFiles:
    - fileName: "SCC.yaml"
      policyName: "add-scc-w20"
    - fileName: "CrontabCRD.yaml"
      policyName: "add-crd-w20"
