---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "cluster-upgrade"
  namespace: "ztp-common"
spec:
  bindingRules:
    common: "true"
  remediationAction: inform
  sourceFiles:
    - fileName: ClusterVersion.yaml
      policyName: "platform-upgrade"
      metadata:
        name: version
      spec:
        channel: "stable-4.14"
        desiredUpdate:
          version: 4.14.1
      status:
        history:
          - version: 4.14.1
            state: "Completed"
