---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: red-vrf
  annotations:
    ran.openshift.io/ztp-deploy-wave: "2"
spec:
  nodeSelector:
    kubernetes.io/hostname: w0.5gc.eric.vlab
  desiredState:
    interfaces:
      - name: red-vrf
        state: up
        type: vrf
        vrf:
          port:
            - bond0.12
          route-table-id: 2
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 12.12.12.254
          next-hop-interface: bond0.12
          table-id: 2
    route-rules:
      config:
        - ip-to: 172.30.0.0/16
          priority: 998
          route-table: 254
        - ip-to: 10.128.0.0/14
          priority: 998
          route-table: 254
