---
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "5gc"
  namespace: "5gc"
spec:
  baseDomain: "eric.vlab"
  cpuPartitioningMode: AllNodes
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "img4.14.6-x86-64-appsub"
  sshPublicKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICGjoGIRGSfiJ8Tv+Qd6S36xuGmeIuFL8w75shdhxy5l ci@only.com"
  clusters:
    - clusterName: "5gc"
      extraManifests:
        searchPaths:
          - extra-manifest/
      networkType: "OVNKubernetes"
      clusterLabels:
        common: true
        htworker: ""
        sites: "n95"
      clusterNetwork:
        - cidr: 10.128.0.0/14
          hostPrefix: 23
        - cidr: fd02::/48
          hostPrefix: 64
      apiVIP: 10.10.10.125
      apiVIPs:
        - 10.10.10.125
        - 2600:52:52:52::125
      ingressVIP: 10.10.10.126
      ingressVIPs:
        - 10.10.10.126
        - 2600:52:52:52::126
      serviceNetwork:
        - 172.30.0.0/16
        - fd03::/112
      machineNetwork:
        - cidr: 10.10.10.0/24
        - cidr: 2600:52:52:52::0/64
      additionalNTPSources:
        - pool.ntp.org
      nodes:
        - hostName: m0.5gc.eric.vlab
          role: "master"
          bmcAddress: redfish-virtualmedia://192.168.100.100:8000/redfish/v1/Systems/11111111-1111-1111-1111-111111111110
          bmcCredentialsName:
            name: "5gc-m0-secret"
          bootMACAddress: "de:ad:be:ff:11:60"
          bootMode: "UEFI"
          rootDeviceHints:
            deviceName: "/dev/vda"
          nodeNetwork:
            interfaces:
              - name: ens3
                macAddress: de:ad:be:ff:11:60
              - name: ens4
                macAddress: de:ad:be:ff:11:61
            config:
              interfaces:
                - &ens3
                  name: ens3
                  type: ethernet
                  state: up
                  ipv4:
                    enabled: false
                  ipv6:
                    enabled: false
                - &ens4
                  name: ens4
                  type: ethernet
                  state: up
                  ipv4:
                    enabled: false
                  ipv6:
                    enabled: false
                - &bond0
                  name: bond0
                  type: bond
                  state: up
                  mtu: 9000
                  #copy-mac-from: ens4 this is not working here https://issues.redhat.com/browse/OCPBUGS-25447
                  link-aggregation:
                    mode: active-backup
                    options:
                      miimon: 100
                      primary: ens3
                    port:
                      - ens3
                      - ens4
                - &bond0-10
                  name: bond0.10
                  type: vlan
                  state: up
                  vlan:
                    base-iface: bond0
                    id: 10
                  ipv4:
                    enabled: true
                    address:
                      - ip: 10.10.10.116
                        prefix-length: 24
                    dhcp: false
                  ipv6:
                    enabled: true
                    autoconf: true
                    dhcp: true
                    auto-dns: false
                    auto-gateway: true
                    auto-routes: true
                - &bond0-11
                  name: bond0.11
                  type: vlan
                  state: up
                  vlan:
                    base-iface: bond0
                    id: 11
                  ipv4:
                    enabled: true
                    address:
                      - ip: 11.11.11.116
                        prefix-length: 24
                    dhcp: false
                  ipv6:
                    enabled: false
              dns-resolver: &dns
                config:
                  server:
                    - 10.10.20.10
              routes: &routes
                config:
                  - destination: 0.0.0.0/0
                    next-hop-address: 10.10.10.1
                    next-hop-interface: bond0.10
                    table-id: 254
        - hostName: m1.5gc.eric.vlab
          role: master
          bmcAddress: redfish-virtualmedia://192.168.100.100:8000/redfish/v1/Systems/11111111-1111-1111-1111-111111111111
          bmcCredentialsName:
            name: "5gc-m1-secret"
          bootMACAddress: "de:ad:be:ff:11:70"
          bootMode: "UEFI"
          rootDeviceHints:
            deviceName: "/dev/vda"
          nodeNetwork:
            interfaces:
              - name: ens3
                macAddress: de:ad:be:ff:11:70
              - name: ens4
                macAddress: de:ad:be:ff:11:71
            config:
              interfaces:
                - *ens3
                - *ens4
                - *bond0
                - <<: *bond0-10
                  ipv4:
                    enabled: true
                    address:
                      - ip: 10.10.10.117
                        prefix-length: 24
                    dhcp: false
                - <<: *bond0-11
                  ipv4:
                    enabled: true
                    address:
                      - ip: 11.11.11.117
                        prefix-length: 24
                    dhcp: false
              dns-resolver: *dns
              routes: *routes
        - hostName: m2.5gc.eric.vlab
          role: master
          bmcAddress: redfish-virtualmedia://192.168.100.100:8000/redfish/v1/Systems/11111111-1111-1111-1111-111111111112
          bmcCredentialsName:
            name: "5gc-m2-secret"
          bootMACAddress: "de:ad:be:ff:11:80"
          bootMode: "UEFI"
          rootDeviceHints:
            deviceName: "/dev/vda"
          nodeNetwork:
            interfaces:
              - name: ens3
                macAddress: de:ad:be:ff:11:80
              - name: ens4
                macAddress: de:ad:be:ff:11:81
            config:
              interfaces:
                - *ens3
                - *ens4
                - *bond0
                - <<: *bond0-10
                  ipv4:
                    enabled: true
                    address:
                      - ip: 10.10.10.118
                        prefix-length: 24
                - <<: *bond0-11
                  ipv4:
                    enabled: true
                    address:
                      - ip: 11.11.11.118
                        prefix-length: 24
                    dhcp: false
              dns-resolver: *dns
              routes: *routes
        - hostName: w1.5gc.eric.vlab
          role: worker
          nodeLabels:
            node-role.kubernetes.io/standard: ""
          bmcAddress: redfish-virtualmedia://192.168.100.100:8000/redfish/v1/Systems/11111111-1111-1111-1111-111111111114
          bmcCredentialsName:
            name: "5gc-w1-secret"
          bootMACAddress: "de:ad:be:ff:11:85"
          bootMode: "UEFI"
          rootDeviceHints:
            deviceName: "/dev/vda"
          nodeNetwork:
            interfaces:
              - name: ens3
                macAddress: de:ad:be:ff:11:85
              - name: ens4
                macAddress: de:ad:be:ff:11:86
            config:
              interfaces:
                - *ens3
                - *ens4
                - *bond0
                - <<: *bond0-10
                  ipv4:
                    enabled: true
                    address:
                      - ip: 10.10.10.120
                        prefix-length: 24
                    dhcp: false
                - <<: *bond0-11
                  ipv4:
                    enabled: true
                    address:
                      - ip: 11.11.11.120
                        prefix-length: 24
                    dhcp: false
              dns-resolver: *dns
              routes: *routes
        - hostName: w2.5gc.eric.vlab
          role: worker
          nodeLabels:
            node-role.kubernetes.io/standard: ""
          bmcAddress: redfish-virtualmedia://192.168.100.100:8000/redfish/v1/Systems/11111111-1111-1111-1111-111111111116
          bmcCredentialsName:
            name: "5gc-w2-secret"
          bootMACAddress: "de:ad:be:ff:11:87"
          bootMode: "UEFI"
          rootDeviceHints:
            deviceName: "/dev/vda"
          nodeNetwork:
            interfaces:
              - name: ens3
                macAddress: de:ad:be:ff:11:87
              - name: ens4
                macAddress: de:ad:be:ff:11:88
            config:
              interfaces:
                - *ens3
                - *ens4
                - *bond0
                - <<: *bond0-10
                  ipv4:
                    enabled: true
                    address:
                      - ip: 10.10.10.121
                        prefix-length: 24
                    dhcp: false
                - <<: *bond0-11
                  ipv4:
                    enabled: true
                    address:
                      - ip: 11.11.11.121
                        prefix-length: 24
                    dhcp: false
              dns-resolver: *dns
              routes: *routes
        - hostName: w0.5gc.eric.vlab
          role: worker
          nodeLabels:
            node-role.kubernetes.io/ht100gb: ""
          bmcAddress: redfish-virtualmedia://192.168.100.100:8000/redfish/v1/Systems/11111111-1111-1111-1111-111111111113
          bmcCredentialsName:
            name: "5gc-w0-secret"
          bootMACAddress: "de:ad:be:ff:11:90"
          bootMode: "UEFI"
          rootDeviceHints:
            deviceName: "/dev/vda"
          nodeNetwork:
            interfaces:
              - name: ens3
                macAddress: de:ad:be:ff:11:90
              - name: ens4
                macAddress: de:ad:be:ff:11:91
              - name: enp3s0
                macAddress: 02:ca:fe:fa:ce:aa
              - name: enp4s0
                macAddress: 02:ca:fe:fa:ce:bb
            config:
              interfaces:
                - name: enp3s0
                  description: dataplane net
                  type: ethernet
                  state: up
                  ipv4:
                    enabled: false
                    dhcp: false
                  ipv6:
                    enabled: false
                    dhcp: false
                - name: enp4s0
                  description: dataplane net
                  type: ethernet
                  state: up
                  ipv4:
                    enabled: false
                    dhcp: false
                  ipv6:
                    enabled: false
                    dhcp: false
                - *ens3
                - *ens4
                - *bond0
                - <<: *bond0-10
                  ipv4:
                    enabled: true
                    address:
                      - ip: 10.10.10.119
                        prefix-length: 24
                    dhcp: false
                - <<: *bond0-11
                  ipv4:
                    enabled: true
                    address:
                      - ip: 11.11.11.119
                        prefix-length: 24
                    dhcp: false
              dns-resolver: *dns
              routes: *routes
