---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks: |-
        [
          {
            "name": "macnet0",
            "namespace": "default"
          }
        ]
  name: withmacvlan-one
  namespace": default
spec:
  nodeSelector:
    kubernetes.io/hostname: m1.5gc.eric.vlab
  containers:
    - name: withmacvlan-c-one
      image: quay.io/karampok/snife:latest
      imagePullPolicy: Always
      securityContext:
        capabilities:
          add:
            - IPC_LOCK
            - SYS_RESOURCE
            - NET_RAW
            - NET_ADMIN
        runAsUser: 0
      command: ["/bin/sh", "-c"]
      args: ["/opt/net/config.sh 172.100.125.100/24; nc -k -l 172.100.125.100 1111"]
      volumeMounts:
        - name: configs
          mountPath: /opt/net/
  volumes:
    - name: configs
      configMap:
        defaultMode: 0777
        name: netconfig
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks: |-
        [
          {
            "name": "macnet0",
            "namespace": "default"
          }
        ]
  name: withmacvlan-two
  namespace": default
spec:
  nodeSelector:
    kubernetes.io/hostname: m2.5gc.eric.vlab
  containers:
    - name: withmacvlan-c-two
      image: quay.io/karampok/snife:latest
      imagePullPolicy: Always
      securityContext:
        capabilities:
          add:
            - IPC_LOCK
            - SYS_RESOURCE
            - NET_RAW
            - NET_ADMIN
        runAsUser: 0
      command: ["/bin/sh", "-c"]
      args: ["/opt/net/config.sh 172.100.125.200/24; nc -k -l 172.100.125.200 2222"]
      volumeMounts:
        - name: configs
          mountPath: /opt/net/
  volumes:
    - name: configs
      configMap:
        defaultMode: 0777
        name: netconfig
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: netconfig
  namespace: default
data:
  config.sh: |
    #! /bin/bash
    set -euo pipefail
    ip link add dev bond0 type bond
    ip link set dev net1 down
    ip link set dev bond0 down
    ip link set dev net1 master bond0
    ip link set dev net1 up
    ip link set dev bond0 up
    ip link add link bond0 name bond0.125 type vlan id 125
    ip link set dev bond0.125 up
    ip a a $1 dev bond0.125

    #ssh lab2 tcpdump -i baremetal -nnn -e|grep "vlan 126\|vlan 125"
