---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: blue
  namespace: metallb-system
spec:
  peerAddress: 10.10.10.1
  peerASN: 65001
  myASN: 7003
  enableGracefulRestart: true
  nodeSelectors:
    - matchLabels:
        node-role.kubernetes.io/worker: ""
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: blue
  namespace: metallb-system
spec:
  ipAddressPools:
    - blue
  peers:
    - blue
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: blue
  namespace: metallb-system
spec:
  autoAssign: false
  addresses:
    - 4.4.4.1/32
    - 2001:db8:0:0:0:0:4:1/128
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-zz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-zz
  template:
    metadata:
      labels:
        app: blue-zz
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      nodeSelector:
            kubernetes.io/hostname: "m0"
      containers:
        - name: sidecar
          image: quay.io/karampok/snife:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
        - name: server
          image: registry.k8s.io/e2e-test-images/agnhost:2.40
          command:
            - /agnhost
            - netexec
            - --http-port=6000
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - name: http
              containerPort: 6000
        - name: app-httpd
          image: quay.io/ocp-edge-qe/rds-metallb-app:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/rh/httpd24/root/var/www/html
              name: rds-index-vol
      volumes:
        - configMap:
            defaultMode: 420
            name: cm-html-index
          name: rds-index-vol
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-html-index
data:
  index.html: |
    <h1>RDS Core MetalLB Graceful Restart</h1>
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.io/address-pool: blue
  name: blue-zz
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ipFamilyPolicy: PreferDualStack
  allocateLoadBalancerNodePorts: false
  ports:
    - name: http
      port: 4444
      protocol: TCP
      targetPort: 8080
  selector:
    app: blue-zz
