---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-two
spec:
  replicas: 2
  selector:
    matchLabels:
      app: green-two
  template:
    metadata:
      labels:
        app: green-two
    spec:
      containers:
        - name: agnhost
          image: quay.io/karampok/snife:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
        - name: server
          image: registry.k8s.io/e2e-test-images/agnhost:2.40
          command:
            - /agnhost
            - netexec
            - --http-port=8080
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - name: http
              containerPort: 8080
        - command: ["bash", "-c"]
          args: ["iperf3 -s -p 60000"]
          image: quay.io/karampok/snife:latest
          imagePullPolicy: Always
          name: iperf3
          ports:
            - name: iperf3
              containerPort: 60000
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: green
    metallb.universe.tf/allow-shared-ip: "key-to-share-two"
  name: green-two-svc-http
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  allocateLoadBalancerNodePorts: false
  ports:
    - name: http
      port: 5555
      protocol: TCP
      targetPort: 8080
  selector:
    app: green-two
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: green
    metallb.universe.tf/allow-shared-ip: "key-to-share-two"
  name: green-two-svc-iperf-tcp
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  allocateLoadBalancerNodePorts: false
  ports:
    - name: tcp
      port: 60000
      protocol: TCP
      targetPort: 60000
  selector:
    app: green-two
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: green
    metallb.universe.tf/allow-shared-ip: "key-to-share-two"
  name: green-two-svc-iperf-udp
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  allocateLoadBalancerNodePorts: false
  ports:
    - name: udp
      port: 60000
      protocol: UDP
      targetPort: 60000
  selector:
    app: green-two
