---
apiVersion: metallb.io/v1beta1
kind: BFDProfile
metadata:
  name: red
  namespace: metallb-system
spec:
  receiveInterval: 20000
  transmitInterval: 10000
  detectMultiplier: 3
  echoInterval: 300
  echoMode: false
  passiveMode: false
  minimumTtl: 254
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: red
  namespace: metallb-system
spec:
  interface: bond0.12
  peerASN: 8012
  myASN: 7003
  holdTime: 60s
  bfdProfile: red
  nodeSelectors:
    - matchLabels:
        node-role.kubernetes.io/worker: ""
        kubernetes.io/hostname: "w1"
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: red
  namespace: metallb-system
spec:
  ipAddressPools:
    - red
  peers:
    - red
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: red
  namespace: metallb-system
spec:
  autoAssign: false
  addresses:
    - 6.6.6.1/32
    - 6.6.6.2/32
