apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: $mcp
  annotations:
    ran.openshift.io/ztp-deploy-wave: "10000"
status:
  conditions:
    - type: Updated
      status: "True"
    - type: Updating
      status: "False"
    - type: Degraded
      status: "False"
  degradedMachineCount: 0
  unavailableMachineCount: 0
