---
apiVersion: ran.openshift.io/v1alpha1
kind: ClusterGroupUpgrade
metadata:
  name: 5gc-x2
  namespace: ztp-install
spec:
  clusters:
    - 5gc
  enable: true
  managedPolicies:
    # - common-config-cluster
    # - common-config-network
    # - common-config-policy
    - common-install-operators
    # - common-platform-upgrade
    # - label-ht-worker-label-nodes
    # - htworker-config-nodes
    # - networks-config-metallb
    # - networks-config-static-routes
  remediationStrategy:
    maxConcurrency: 1
    timeout: 240
