---
apiVersion: ran.openshift.io/v1alpha1
kind: ClusterGroupUpgrade
metadata:
  name: 5gc-x
  namespace: ztp-install
spec:
  clusters:
    - 5gc
  enable: true
  managedPolicies:
    # - common-config-cluster
    # - common-config-network
    # - common-install-operators
    # - common-config-operators
    # - common-config-policy
    # - common-platform-upgrade
    # - label-ht-worker-label-nodes
    # - htworker-config-nodes
    # - htworker-config-sriov-sn
    # - htworker-config-sriov-snnp
    # - htworker-config-virt-vfio-noiommu
    # - networks-config-metallb
    # - networks-config-static-routes
    - networks-config-bgp-learning
    - networks-config-metallb-red
  remediationStrategy:
    maxConcurrency: 1
    timeout: 240
