---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 40-wipe-sda
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      disks:
        - device: /dev/sda
          wipe_table: true
