---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: odf-operator
  namespace: openshift-storage
  annotations:
    ran.openshift.io/ztp-deploy-wave: "2"
spec:
  channel: "stable-4.12"
  installPlanApproval: Manual
  name: odf-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
status:
  state: AtLatestKnown
