---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
resources:
  - https://github.com/redhat-cop/gitops-catalog/advanced-cluster-management/instance/base?ref=main
  - 10-lvm-instance.yaml
  - 20-agent-service-config.yaml
