---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hub-operators-deployment
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: hub/operators-deployment
    repoURL: 'https://github.com/karampok/telco-ocp-lab.git'
    targetRevision: dev
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 1
        maxDuration: 3m0s
      limit: 1000
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hub-operators-config
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: hub/operators-config
    repoURL: 'https://github.com/karampok/telco-ocp-lab.git'
    targetRevision: dev
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 1
        maxDuration: 3m0s
      limit: 1000
