---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
resources:
  - https://github.com/redhat-cop/gitops-catalog/advanced-cluster-management/operator/base?ref=main
  - https://github.com/redhat-cop/gitops-catalog/lvm-storage/operator/base?ref=main
  - https://github.com/redhat-cop/gitops-catalog/topology-aware-lifecycle-manager-operator/base?ref=main
  - https://github.com/redhat-cop/gitops-catalog/advanced-cluster-management/instance/base?ref=main
  - 10-lvm-instance.yaml
  - 20-agent-service-config.yaml
  - 10-provisioning.yaml
patches:
  - target:
      kind: Subscription
      name: advanced-cluster-management
    patch: |-
      - op: replace
        path: /spec/channel
        value: release-2.8
  - target:
      group: operators.coreos.com
      kind: Subscription
      name: lvms-operator
      namespace: openshift-storage
      version: v1alpha1
    patch: |-
      - op: replace
        path: /spec/channel
        value: stable-4.13
  - target:
      group: operators.coreos.com
      kind: Subscription
      name: openshift-topology-aware-lifecycle-manager-subscription
      namespace: openshift-operators
      version: v1alpha1
    patch: |-
      - op: replace
        path: /spec/channel
        value: stable
# patchesJson6902:
#   - target:
#       group: argoproj.io
#       version: v1alpha1
#       kind: ArgoCD
#       name: openshift-gitops
#     path: argocd-openshift-gitops-patch.json
