---
apiVersion: ran.openshift.io/v1alpha1
kind: ClusterGroupUpgrade
metadata:
  name: 5gc-x
  namespace: ztp-install
spec:
  clusters:
    - 5gc
  enable: true
  managedPolicies:
    - htworker-config-ht-node
    - networks-config-operators-metallb-w10
    - htworker-config-ht-node
    - htworker-config-operator-sriov-w10
    - networks-config-bgp-learning-w11
    - networks-config-metallb-red-w12
    - networks-config-metallb-w12
    - post-add-scc-w20
    - post-add-crd-w20
    - htworker-config-sriov-snnp-w100
    - htworker-config-sriov-sn-w100
    - cluster-ocp-version
    - validator-validate-sriov-w1000
    - validator-validate-mcp
  remediationStrategy:
    maxConcurrency: 1
    timeout: 240
