---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: red
spec:
  replicas: 1
  selector:
    matchLabels:
      app: red
  template:
    metadata:
      labels:
        app: red
    spec:
      containers:
        - name: agnhost
          image: quay.io/karampok/snife:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
        - name: server
          image: registry.k8s.io/e2e-test-images/agnhost:2.40
          command:
            - /agnhost
            - netexec
            - --http-port=8080
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - name: http
              containerPort: 8080
        - command: ["bash", "-c"]
          args: ["iperf3 -s -p 60000"]
          image: quay.io/karampok/snife:latest
          imagePullPolicy: Always
          name: iperf3
          ports:
            - name: iperf3
              containerPort: 60000
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: red
    metallb.universe.tf/allow-shared-ip: "key-to-share-red"
  name: red-svc-http
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  allocateLoadBalancerNodePorts: false
  ports:
    - name: http
      port: 5555
      protocol: TCP
      targetPort: 8080
  selector:
    app: red
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: red
    metallb.universe.tf/allow-shared-ip: "key-to-share-red"
  name: red-svc-iperf-tcp
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  allocateLoadBalancerNodePorts: false
  ports:
    - name: tcp
      port: 60000
      protocol: TCP
      targetPort: 60000
  selector:
    app: red
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: red
    metallb.universe.tf/allow-shared-ip: "key-to-share-red"
  name: red-svc-iperf-udp
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  allocateLoadBalancerNodePorts: false
  ports:
    - name: udp
      port: 60000
      protocol: UDP
      targetPort: 60000
  selector:
    app: red

# show bgp vrf red ipv4 summary
# from red
# alias urlencode="python3 -c \"import sys, urllib.parse; print(urllib.parse.quote(''.join(sys.stdin.readlines())))\""
# curl -s http://6.6.6.1/shell?cmd="$(echo "env|grep -i node" | urlencode)"|jq -r '.output'
