---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: greenpeers
  namespace: metallb-system
  annotations:
    ran.openshift.io/ztp-deploy-wave: "10"
spec:
  keepaliveTime: 0s
  peerAddress:
  peerASN:
  myASN:
  holdTime: 3m0s
  passwordSecret: {}
  bfdProfile: bfd-profile
  peerPort: 179
