---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: metallb-operator
  namespace: openshift-marketplace
  annotations:
    target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
    ran.openshift.io/ztp-deploy-wave: "10"
spec:
  displayName: Openshift Metallb Operator
  icon:
    base64data: ""
    mediatype: ""
  #image: quay.io/openshift-kni/performance-addon-operator-index:4.9-snapshot
  image: $imageUrl
  publisher: Red Hat
  sourceType: grpc
