---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name:
  namespace: metallb-system
  annotations:
    ran.openshift.io/ztp-deploy-wave: "10"
spec:
  autoAssign: false
  avoidBuggyIPs: false
  addresses:
