---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: metallb-operator-sub
  namespace: metallb-system
  labels:
    operators.coreos.com/metallb-operator.metallb-system: ""
  annotations:
    ran.openshift.io/ztp-deploy-wave: "2"
spec:
  channel: stable
  name: metallb-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Manual
status:
  state: AtLatestKnown
